# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    # -- Router config ajoutée ici --
    router:
        utf8: true

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

# En prod, on assouplit strict_requirements
when@prod:
    framework:
        router:
            strict_requirements: null

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
