# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm                           # ← required!
    mappings:
        profil_image:                        # ← must match the annotation below
            uri_prefix: /uploads/profiles
            upload_destination: '%kernel.project_dir%/public/uploads/profiles'
            namer: vich_uploader.namer_uniqid # ← gives you unique filenames
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: false
